### ISSUE TITLE
Encounter error when get grasps

### ISSUE THREAD

**Issue by Jar7visZ** [jimazeyu/GraspSplats#10]
Hi, I got this output when I clicked on "Generate Global Grasp" or "Generate Object Grasps" on the gui for example_data given in the repository.How can I solve the problem?
Thanks for your help!
```
Generating object grasps
Object grasps generated
0 grasps generated
Traceback (most recent call last):
  File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/infra/_infra.py", line 449, in wrapped
    inner()
  File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/infra/_infra.py", line 257, in <lambda>
    lambda: self._handle_incoming_message(client_id, message)
  File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/infra/_infra.py", line 94, in _handle_incoming_message
    cb(client_id, message)
  File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/_gui_api.py", line 157, in _handle_gui_updates
    cb(GuiEvent(client, client_id, handle))
  File "/home/ubuntu/hdd3/JarvisZ/GraspSplats-main/realbot_ui.py", line 616, in _
    local_object_grasp_scores_visual = (local_object_grasp_scores_visual - np.min(local_object_grasp_scores_visual)) / (np.max(local_object_grasp_scores_visual) - np.min(local_object_grasp_scores_visual))
  File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2953, in min
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by RogerRafa** [comment]
Hi, I noticed that you have already opened the GUI interface. May I ask what the actual URL you are using is? Is it http://0.0.0.0:8080/? When I open this URL, it shows that the page cannot be accessed.

**Comment by Jar7visZ** [comment]
I can open this page after successfully run the commend ```python realbot_ui.py -m outputs/example_data```,maybe you haven't run the code properly,or you can try this command```pip install viser==0.1.10 roboticstoolbox-python transforms3d```and```pip install panda_python```

> Hi, I noticed that you have already opened the GUI interface. May I ask what the actual URL you are using is? Is it http://0.0.0.0:8080/? When I open this URL, it shows that the page cannot be accessed.

**Comment by z-x-j** [comment]
![Image](https://github.com/user-attachments/assets/ddebfc9b-b15f-405c-bcf6-1340ad229614)  这是我的抓取结果，这看起来不对

**Comment by Jar7visZ** [comment]
> ![Image](https://github.com/user-attachments/assets/ddebfc9b-b15f-405c-bcf6-1340ad229614) 这是我的抓取结果，这看起来不对

你的问题可能是操作不当，可以照着源代码中的步骤完成。
<img width="614" alt="Image" src="https://github.com/user-attachments/assets/c5888e1d-f515-4eb2-9e71-984000d21744" />

**Comment by z-x-j** [comment]
我是严格按照上面的步骤进行的，但是点击Query 按钮后，螺丝刀的位置不对

**Comment by mingchisun03** [comment]
> Hi, I got this output when I clicked on "Generate Global Grasp" or "Generate Object Grasps" on the gui for example_data given in the repository.How can I solve the problem? Thanks for your help!
> 
> ```
> Generating object grasps
> Object grasps generated
> 0 grasps generated
> Traceback (most recent call last):
>   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/infra/_infra.py", line 449, in wrapped
>     inner()
>   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/infra/_infra.py", line 257, in <lambda>
>     lambda: self._handle_incoming_message(client_id, message)
>   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/infra/_infra.py", line 94, in _handle_incoming_message
>     cb(client_id, message)
>   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/_gui_api.py", line 157, in _handle_gui_updates
>     cb(GuiEvent(client, client_id, handle))
>   File "/home/ubuntu/hdd3/JarvisZ/GraspSplats-main/realbot_ui.py", line 616, in _
>     local_object_grasp_scores_visual = (local_object_grasp_scores_visual - np.min(local_object_grasp_scores_visual)) / (np.max(local_object_grasp_scores_visual) - np.min(local_object_grasp_scores_visual))
>   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2953, in min
>     return _wrapreduction(a, np.minimum, 'min', axis, None, out,
>   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
>     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> ValueError: zero-size array to reduction operation minimum which has no identity
> ```

Hello, I noticed that you also had such a problem, how did you solve it? Looking forward to your reply!

**Comment by Jar7visZ** [comment]
> > Hi, I got this output when I clicked on "Generate Global Grasp" or "Generate Object Grasps" on the gui for example_data given in the repository.How can I solve the problem? Thanks for your help!
> > ```
> > Generating object grasps
> > Object grasps generated
> > 0 grasps generated
> > Traceback (most recent call last):
> >   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/infra/_infra.py", line 449, in wrapped
> >     inner()
> >   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/infra/_infra.py", line 257, in <lambda>
> >     lambda: self._handle_incoming_message(client_id, message)
> >   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/infra/_infra.py", line 94, in _handle_incoming_message
> >     cb(client_id, message)
> >   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/viser/_gui_api.py", line 157, in _handle_gui_updates
> >     cb(GuiEvent(client, client_id, handle))
> >   File "/home/ubuntu/hdd3/JarvisZ/GraspSplats-main/realbot_ui.py", line 616, in _
> >     local_object_grasp_scores_visual = (local_object_grasp_scores_visual - np.min(local_object_grasp_scores_visual)) / (np.max(local_object_grasp_scores_visual) - np.min(local_object_grasp_scores_visual))
> >   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2953, in min
> >     return _wrapreduction(a, np.minimum, 'min', axis, None, out,
> >   File "/home/zjw/miniconda3/envs/gsgrasper/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 88, in _wrapreduction
> >     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
> > ValueError: zero-size array to reduction operation minimum which has no identity
> > ```
> 
> Hello, I noticed that you also had such a problem, how did you solve it? Looking forward to your reply!

I damaged my environment variables while installing gpd. After I fixed them, I was able to run it correctly. You can check whether your gpd is installed correctly or verify if your environment variables are set up properly.

**Comment by wh-BOS** [comment]
Hello, I want to know if you have used your own data to run "run realbot_ui.py" and successfully achieved the effect of this project
