### ISSUE TITLE
Need help in resolving GPD error (encountered while generate global grasps)

### ISSUE THREAD

**Issue by PannagaS** [jimazeyu/GraspSplats#9]
Hi, I am getting this output when I click on "Generate Global Grasp" on the gui for example_data given in the repository. How do I resolve this? Any help is appreciated. 

```
Traceback (most recent call last):
  File "/home/pannaga/micromamba/envs/grasp_splats/lib/python3.10/site-packages/viser/infra/_infra.py", line 449, in wrapped
    inner()
  File "/home/pannaga/micromamba/envs/grasp_splats/lib/python3.10/site-packages/viser/infra/_infra.py", line 257, in <lambda>
    lambda: self._handle_incoming_message(client_id, message)
  File "/home/pannaga/micromamba/envs/grasp_splats/lib/python3.10/site-packages/viser/infra/_infra.py", line 94, in _handle_incoming_message
    cb(client_id, message)
  File "/home/pannaga/micromamba/envs/grasp_splats/lib/python3.10/site-packages/viser/_gui_api.py", line 157, in _handle_gui_updates
    cb(GuiEvent(client, client_id, handle))
  File "/home/pannaga/Desktop/GraspSplats/realbot_ui.py", line 358, in _
    pose_matrices, scores = grasping_utils.sample_grasps(saved_path, if_global=True)
  File "/home/pannaga/Desktop/GraspSplats/grasping/grasping_utils.py", line 12, in sample_grasps
    result = subprocess.run(command, capture_output=True, text=True)
  File "/home/pannaga/micromamba/envs/grasp_splats/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/pannaga/micromamba/envs/grasp_splats/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/pannaga/micromamba/envs/grasp_splats/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './gpd/build/detect_grasps'
```

Thanks!

**Comment by jimazeyu** [comment]
You should build gpd first, after that you may check if the file exists.
